version: "3"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "10002:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - TZ=Asia/Kolkata
    volumes:
      - /data/sonarqube/sonarqube_data/sonar:/opt/sonarqube/conf
      - /data/sonarqube/sonarqube_data/sonar:/opt/sonarqube/data
      - /data/sonarqube/sonarqube_data/sonar:/opt/sonarqube/extensions
      - /data/sonarqube/sonarqube_data/sonar:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: sonarqube_pgsql
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - TZ=Asia/Kolkata
    volumes:
      - /data/sonarqube/sonarqube_data/postgres/data:/var/lib/postgresql/data

networks:
  sonarnet: